[package]
name = "ctp-alone"
version = "0.1.0"
authors = ["caleb.xiang <caleb.xiang@sinobot.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2"
memchr = "2.3"
simple-error = "0.2"
time = "0.2"
